export const storeTypes = {
    USER: 'USER',
    FIRST_TIME: 'FIRST_TIME',
    TICKETS: 'TICKETS',
    ACTIVE_TICKET: 'ACTIVE_TICKET',
    TICKET_HISTORY: 'TICKET_HISTORY',
    OPERATORS: 'OPERATORS',
    ADMINS: 'ADMINS'
};